### ISSUE TITLE
CDN-based JS is not being built

### ISSUE THREAD

**Issue by onexdata** [singerla/quasar-json-tree-editor#2]
Alll the CSS looks like it exists, but not the JS, Would have loved to use this in a project today but no umd or other builds available. See https://cdn.jsdelivr.net/npm/quasar-ui-json-tree-editor/dist/

**Comment by singerla** [comment]
Hi! Please be patient, this is a work in progress. I'm still playing around with `vue-draggable-plus` and going to release a working version as soon as possible.

**Comment by singerla** [comment]
Hi! please check out v0.2.0. I'd be happy for feedback of all kinds! :)
